# Generated by Django 5.2.4 on 2025-07-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
        ("store", "0003_remove_store_manager_id_remove_storeitem_product_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart_id",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="storeitem_id",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="cart.cart"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="storeitem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.storeitem",
            ),
        ),
    ]
