# Generated by Django 5.2.4 on 2025-07-19 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_remove_productimage_product_id_productimage_product_and_more",
        ),
        ("store", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="manager_id",
        ),
        migrations.RemoveField(
            model_name="storeitem",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="storeitem",
            name="store_id",
        ),
        migrations.AddField(
            model_name="store",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="store",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.store"
            ),
        ),
    ]
