# Generated by Django 5.2.4 on 2025-07-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="manager",
            new_name="owner",
        ),
    ]
