# Generated by Django 5.2.4 on 2025-07-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="store",
        ),
    ]
