CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "first_name" varchar(150) NOT NULL,
  "last_name" varchar(150) NOT NULL,
  "email" varchar(254) NOT NULL,
  "username" varchar(150) NOT NULL,
  "phone" varchar(15) NOT NULL,
  "password" varchar(128) NOT NULL,
  "role" varchar(1) NOT NULL,
  "is_superuser" bool NOT NULL,
  "is_staff" bool NOT NULL,
  "is_active" bool NOT NULL,
  "date_joined" datetime NOT NULL,
  "last_login" datetime,
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "address" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int,
  "store_id" int,
  "address" text NOT NULL,
  "city" varchar(50),
  "state" varchar(100),
  "postal_code" text,
  "is_default" bool DEFAULT 'False',
  "phone" text NOT NULL,
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar(256) NOT NULL,
  "slug" varchar(256) NOT NULL,
  "brand" varchar(100) NOT NULL,
  "description" text NOT NULL,
  "status" varchar DEFAULT 'draft',
  "category_id" int,
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "productimage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "product_id" int NOT NULL,
  "image" image DEFAULT 'default.jpg'
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "slug" varchar(150) NOT NULL,
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "store" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(150) NOT NULL,
  "manager_id" int NOT NULL,
  "description" text,
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "storeitem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "product_id" int,
  "store_id" int,
  "price" decimal(10,2) NOT NULL,
  "quantity" int DEFAULT 0,
  "is_listed" bool DEFAULT 'False',
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "cart" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "discount_id" int NOT NULL,
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "cartitem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cart_id" int NOT NULL,
  "storeitem_id" in NOT NULL,
  "price_at_time" decimal(10,2),
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "discount_id" int NOT NULL,
  "address_id" int NOT NULL,
  "status" varchar DEFAULT 'pending',
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "orderitem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" int NOT NULL,
  "storeitem_id" in NOT NULL,
  "price_at_purchase" decimal(10,2),
  "quantity" int DEFAULT 0,
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "discount" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "code" varchar(50) NOT NULL,
  "discount_type" varchar NOT NULL,
  "value" decimal(10,2) NOT NULL,
  "start_time" datetime,
  "end_time" datetime,
  "usage_limit" int,
  "per_user_limit" int,
  "is_active" bool DEFAULT 'True',
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "comment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "product_id" int,
  "store_id" int,
  "message" text NOT NULL,
  "is_published" bool DEFAULT 'False',
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

CREATE TABLE "payment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" int NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "method" varchar(20) DEFAULT 'zarinpal',
  "status" varchar(20) DEFAULT 'initiated',
  "authority_code" varchar(150),
  "transaction_id" varchar(150),
  "paid_at" datetime,
  "created_at" datetime NOT NULL DEFAULT 'auto_now_add = True',
  "updated_at" datetime NOT NULL DEFAULT 'auto_now = True',
  "is_deleted" bool DEFAULT 'False'
);

ALTER TABLE "address" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

CREATE TABLE "product_category" (
  "product_category_id" int,
  "category_id" int,
  PRIMARY KEY ("product_category_id", "category_id")
);

ALTER TABLE "product_category" ADD FOREIGN KEY ("product_category_id") REFERENCES "product" ("category_id");

ALTER TABLE "product_category" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");


ALTER TABLE "store" ADD FOREIGN KEY ("manager_id") REFERENCES "user" ("id");

ALTER TABLE "address" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");

ALTER TABLE "storeitem" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");

ALTER TABLE "storeitem" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "cart" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "cartitem" ADD FOREIGN KEY ("cart_id") REFERENCES "cart" ("id");

ALTER TABLE "cartitem" ADD FOREIGN KEY ("storeitem_id") REFERENCES "storeitem" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id");

ALTER TABLE "orderitem" ADD FOREIGN KEY ("storeitem_id") REFERENCES "storeitem" ("id");

ALTER TABLE "orderitem" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "cart" ADD FOREIGN KEY ("discount_id") REFERENCES "discount" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("discount_id") REFERENCES "discount" ("id");

ALTER TABLE "productimage" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "payment" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");
