# Generated by Django 5.2.4 on 2025-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
